[package]
name = "splay"
version = "0.1.0"
description = "Splay tree library"
repository = "https://github.com/chenyan2002/motoko-splay"
keywords = ["splay", "map", "collection"]
license = "Apache-2.0"
