#!/usr/bin/env bash

set -e

for i in 0 2 4 8 16 32; do
  if [ $i -gt 0 ]; then
    echo "retrying in $i seconds" 1>&2
    sleep $i
  fi

  if output=$(mops sources | grep -v "reducing threads"); then
    echo "$output"
    exit 0
  fi
  echo "failed with output: $output" 1>&2
done

exit 1
