= Node End-to-End Tests

== High level overview

These tests are composed of two parts;

1. a Nix script that installs the Agent in the execution location, as if it was an NPM
   package. This is done by building the NPM Package, and the JS Agent derivation outputting
   2 outputs; the NPM package itself (in a packed format), and its node_modules which are
   then copied in the execution folder for these tests.
2. a Jest framework in TypeScript that runs and validate the tests.

The result is you build your tests as you would with Jest. You can import the JavaScript
agent by using `import * as agent from '@dfinity/agent'` which is as
close as it can be to the real world.

== Starting / Stopping the Replica

The `setup` Jest step starts the replica using `dfx replica`. The `teardown` step sends
a SIGTERM to the `dfx` process. Nix will wait for all children and descendants to be
stopped, so Nix will timeout and fail if the replica isn't properly killed.

== Adding New Tests

Adding a test is just a matter of having a file with a `.ts` extension anywhere outside
the root directory of tests and the `utils/` folder. This is driven by the
`jest.config.js` file which has a pattern matching all those files.

We don't force users to have a `.test.ts` extension as this whole folder is meant to be
tests. It's just simpler that way.

== Using HttpAgent

The `utils/` folder contain an `agent.ts` file which exports an `HttpAgent` instance
which connects to the testing Replica. Unless required by your test to have a special
agent configuration, you should always reuse that one.

== Creating and Using Canisters

Right now, the way to add a canister is to manually build it and check in the canisters
WASM. This is a limitation of the current setup and will (hopefully) go away soon.

Once the WASM is checked in, a canister `.ts` should be added which exports a factory.
That factory reads the WASM, creates an actor with a random canisterId, builds the IDL
manually (currently) and install the canister on the Replica. A good example of this
can be seen in `utils/canisters/counter.ts`.

= TODOs

- [ ] Add a dfx project derivation which generates the WASM and IDL through Nix
      so it doesn't have to be checked in.
- [ ] Also, reuse canister IDs exposed by the dfx project derivation above instead
      of generating a random one. This is important for testing canisters which
      have inter-canister calls.
