= Contributing to the DFINITY SDK

== Developing `dfx`

Run `nix-shell` in the root directory of this repo to bring the right version
of `rustc` and `cargo` into scope.

Inside the shell use `cargo` to build and test the Rust packages (crates).

[source,bash]
----
sdk $ nix-shell
[nix-shell:~/d/sdk]$ cargo build
[nix-shell:~/d/sdk]$ cargo test
----

Open a second window to run `dfx`, since we usually run it in a different
subdirectory and running it does not require a `nix-shell`.

[source,bash]
----
sdk $ alias dfx=$(pwd)/target/debug/dfx
sdk $ dfx --version
dfx 0.5.7-1-gad81116
----

=== Other Development Workflows

==== Running End-to-End Tests Locally

[source,bash]
----
sdk $ nix-shell -A e2e-tests default.nix
[nix-shell:~/d/sdk]$ cd e2e/bats
[nix-shell:~/d/sdk]$ bats *.bash
----

==== Running End-to-End Tests Locally Against Reference IC

This runs the end-to-end tests against the
https://github.com/dfinity-lab/ic-ref[reference implementation of the Internet Computer].

[source,bash]
----
sdk $ nix-shell -A e2e-tests-ic-ref default.nix
[nix-shell:~/d/sdk]$ cd e2e/bats
[nix-shell:~/d/sdk]$ USE_IC_REF=1 bats *.bash
----

==== Build `dfx`, then use it to create and build a new dfx project

In order to build locally, you will have to install the javascript agent.
(It doesn't seem right that this is required, though).

[source,bash]
----
sdk $ cd ~/w
w $ dfx new abc
w $ cd abc
abc $ dfx canister create --all
abc $ dfx build                   # (fails)
abc $ npm install ~/d/sdk/src/agent/javascript
abc $ dfx build                   # (fails - webpack missing)
abc $ npm install
abc $ dfx build                   # (succeeds)
----


==== Running `dfx` in a Debugger

While there are many OS/IDE variants where this can work, this document provides
a specific example in order to make the instructions easier to follow.

The key is to use a `nix-shell` to provide the `DFX_ASSETS` environment variable for `dfx`.

This example assumes that your git workspaces are under `~/d` and
your `dfx` workspaces are under `~/w`, but they can be anywhere.

===== Debugging `dfx` in JetBrains IDEs on OSX

. Install https://www.rust-lang.org/tools/install[Rust]

. Switch to the version of the rust toolchain from the https://github.com/dfinity-lab/common/blob/master/nix/overlays/rust.nix#L12[common repo]
+
[source,bash]
----
$ rustup toolchain install 1.41.1
$ rustup default 1.41.1
----
+
. Install https://www.jetbrains.com/idea/[IDEA Ultimate] or https://www.jetbrains.com/clion/[CLion], and the Rust plugin.

. Install https://brew.sh/[Homebrew] and required packages:
+
[source,bash]
----
$ brew install openssl cmake
----

. Start a `nix-shell` and obtain `DFX_ASSETS`.
+
Leave this `nix-shell` open.
+
[source,bash]
----
sdk $ nix-shell
[nix-shell:~/d/sdk]$ echo $DFX_ASSETS
/nix/store/g419n569py1gas7642q9jf5vh19xzp3y-dfx-assets
----

. Launch your IDE and then `File | Open... | ~/d/sdk/Cargo.toml`
You should briefly see a small popup that says `Using rustup`.

. In the Project window, navigate to `src/dfx/src/main.rs` and right-click `Run 'Run dfx'`
+
It will build, but fail to run with an error like this:
+
----
thread 'main' panicked at 'Cannot find DFX_ASSETS: NotPresent', src/libcore/result.rs:1188:5
----

. Fix the Run/Debug Configuration
+
By default, it will be set up to run `dfx` without parameters
in the `sdk` workspace directory.
+
We'll set up a configuration to run `dfx new <project>`, which we can duplicate
and alter for other commands, by making these changes:
+
* Change the `Name` field to indicate which command we are running
* Specify the `--manifest-path` for `cargo run`
* Add command-line arguments for `dfx`
* Provide the `DFX_ASSETS` environment variable
* Change the working directory to where we want to run `dfx`
+
Before:
+
----
Name: Run dfx
Command: run --package dfx --bin dfx
Environment variables:
Working directory: <home>/d/sdk
----
+
After:
+
----
Name: dfx new dfxdebug
Command: run --manifest-path <home>/d/sdk/Cargo.toml --package dfx --bin dfx new someproject
Environment variables: DFX_ASSETS=<DFX_ASSETS path from nix-shell>
Working directory: <home>/w
----

. Run or set breakpoints and debug.

== Conventional Commits

We use a squash & merge PR strategy, which means that each PR will result in exactly
one commit in `master`. When releasing, we are using the history to know which commits
and what messages make into the release notes (and what needs to be documented).

That means we enforce conventional commits to help us distinguish those commits. When
creating a PR, we have a special check that validate the PR title and will fail if it
doesn't follow the conventional commit standard (see
https://www.conventionalcommits.org/).

What that means is your PR title should start with one of the following prefix:

* `feat:`. Your PR implement a new feature and should be documented. If version numbers
  were following semver, this would mean that we need to put the PR in the next minor.
* `fix:`. Your PR fixes an issue. There should be a link to the issue being fixed.
  In SemVer, this would be merged in both minor and patch branches.
* `refactor:`, `chore:`, `build:`, `docs:`, `test:` does not affect the release notes
  and will be ignored.
* `release:`. Your PR is for tagging a release and should be ignored, but will be
  a break point for the log history when doing release notes.

== Documentation

https://hydra.oregon.dfinity.build/latest/dfinity-ci-build/sdk/dfx.doc.x86_64-linux/dfx/index.html[Latest cargo docs].

== CI

To run the CI job manually run either:

[source,bash]
nix-build ci/ci.nix -A dfx[.x86_64-linux|.x86_64-darwin]

== Dependencies

=== Licenses

https://hydra.oregon.dfinity.build/latest/dfinity-ci-build/sdk/licenses.dfx.x86_64-linux/licenses.dfinity-sdk-dfx.html[Latest licenses of all dependencies of dfx (build for x86_64-linux)].

=== Visualization

https://hydra.oregon.dfinity.build/latest/dfinity-ci-build/sdk/dfx.x86_64-linux/dfx/cargo-graph.svg[Access the latest graph of dependencies between crates of the `dfx` crate (build for x86_64-linux)].

To build and visualize this graph locally run:

[source,bash]
open $(nix-build -A dfx.doc)/dfx/cargo-graph.svg
