queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=hydra:dfinity-ci-build:evaluation
      - status-success=hydra:dfinity-ci-build:sdk:required
      - status-success=audit:required
      - status-success=e2e:required
      - status-success=fmt:required
      - status-success=lint:required
      - status-success=prepare-dfx-assets:required
      - base=master
      - label=automerge-squash

pull_request_rules:
  - name: Automatic merge (squash)
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=hydra:dfinity-ci-build:evaluation
      - status-success=hydra:dfinity-ci-build:sdk:required
      - status-success=audit:required
      - status-success=e2e:required
      - status-success=fmt:required
      - status-success=lint:required
      - status-success=prepare-dfx-assets:required
      - base=master
      - label=automerge-squash
    actions:
      merge:
        method: merge
        name: default
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}
      delete_head_branch: {}
  - name: Clean up automerge tags
    conditions:
      - closed
    actions:
      label:
        remove:
        - automerge-squash
  - name: Auto-approve auto-PRs
    conditions:
      - author=dfinity-bot
    actions:
      review:
        type: APPROVE
        message: This bot trusts that bot
