= 0.6.24

== DFX

- feat: install `dfx` by version or tag (#1426)

This feature adds a new dfx command `toolchain` which have intuitive subcommands.
The toolchain specifiers can be a complete version number, major minor version, or a tag name.

[source, bash]
----
dfx toolchain install 0.6.24 # complete version
dfx toolchain install 0.6    # major minor
dfx toolchain install latest # tag name
dfx toolchain default latest
dfx toolchain list
dfx toolchain uninstall latest
----

- fix: onboarding related fixups (#1420)

Now that the Mercury Alpha application subnetwork is up and we are getting ready to onboard devs, the dfx error message for wallet creation has changed:
For example,
[source, bash]
----
dfx canister --network=alpha create hello
Creating canister "hello"...
Creating the canister using the wallet canister...
Creating a wallet canister on the alpha network.
Unable to create a wallet canister on alpha:
The Replica returned an error: code 3, message: "Sender not authorized to use method."
Wallet canisters on alpha may only be created by an administrator.
Please submit your Principal ("dfx identity get-principal") in the intake form to have one created for you.
----

- feat: add deploy wallet subcommand to identity (#1414)

This feature adds the deploy-wallet subcommand to the dfx identity.
The User provides the ID of the canister onto which the wallet WASM is deployed.

[source, bash]
----
dfx identity deploy-wallet --help
dfx-identity-deploy-wallet
Installs the wallet WASM to the provided canister id

USAGE:
    dfx identity deploy-wallet <canister-id>

ARGS:
    <canister-id>    The ID of the canister where the wallet WASM will be deployed

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
----

= 0.6.22

== DFX

- feat: dfx call random value when argument is not provided (#1376)

- fix: canister call can take canister ids for local canisters even if … (#1368)
- fix: address panic in dfx replica command (#1338)
- fix: dfx new webpack.config.js does not encourage running 'js' through ts-… (#1341)

== Sample apps

- There have been updates, improvements, and new sample apps added to thelink:https://github.com/dfinity/examples/tree/master/motoko[examples] repository.
+
All of Motoko sample apps in the link:https://github.com/dfinity/examples/tree/master/motoko[examples] repository have been updated to work with the latest release of the SDK.
+
There are new sample apps to illustrate using arrays (link:https://github.com/dfinity/examples/tree/master/motoko/quicksort[Quicksort]) and building create/read/update/delete (CRUD) operations for a web application link:https://github.com/dfinity/examples/tree/master/motoko/superheroes[Superheroes].

- The link:https://github.com/dfinity/linkedup:[LinkedUp] sample application has been updated to work with the latest release of Motoko and the SDK.

== Motoko

== Agents

== Canister Development Kit (CDK)
