blank_issues_enabled: true
contact_links:
  - name: Question about dfx use
    url: https://forum.dfinity.org/
    about: Please ask and answer questions about how to use dfx in the developer forum.
  - name: Feature Request
    url: https://github.com/dfinity/sdk/discussions
    about: Please create and upvote feature requests in Discussions