name: Check frontend canister build

on:
  push:
    branches:
      - master
    paths:
      - src/distributed/assetstorage.wasm.gz
      - src/canisters/frontend/ic-certified-assets/**
      - src/canisters/frontend/ic-frontend-canister/**
  pull_request:
    paths:
      - src/distributed/assetstorage.wasm.gz
      - src/canisters/frontend/ic-certified-assets/**
      - src/canisters/frontend/ic-frontend-canister/**

env:
  # When getting Rust dependencies, retry on network error:
  CARGO_NET_RETRY: 10
  # Use the local .curlrc
  CURL_HOME: .

jobs:
  frontend:
    runs-on: ubuntu-latest
    name: frontend-canister-up-to-date:required
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build frontend canister
        run: |
          ./scripts/update-frontend-canister.sh --release-build
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: assetstorage
          path: ${{ github.workspace }}/src/distributed/assetstorage.wasm.gz
      - name: Compare
        run: |
          if [ "$(git diff src/distributed/assetstorage.wasm.gz)" != "" ]
          then
            echo "src/distributed/assetstorage.wasm.gz needs to be updated; run ./scripts/update-frontend-canister.sh --release-build"
            exit 1
          fi
