name: Check shell scripts
on:
  pull_request:
    paths:
      - 'e2e/**'
      - '.github/**'
      - 'scripts/release.sh'
      - 'scripts/prepare-dfx-assets.sh'
      - 'scripts/update-frontend-canister.sh'
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # When getting Rust dependencies, retry on network error:
  CARGO_NET_RETRY: 10
  # Use the local .curlrc
  CURL_HOME: .

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check e2e scripts
        run: shellcheck e2e/**/*.*sh
      - name: Check scripts/
        run: shellcheck scripts/*.sh

