= IDL Serialization library in Rust

== Using the library
* Serialization
[source,rust]
#[macro_use]
extern crate serde_idl;
Encode!(&42, &Some(42), &[1,2,3])
// Encode! macro expands to:
IDLBuilder::new().arg(&42).arg(&Some(42)).arg(&[1,2,3]).to_vec().unwrap(),


* Derive serialization trait and inspect IDL type
[source,rust]
#[derive(IDLType)]
struct List { head: i32, tail: Option<Box<List>> }
let list = List { head: 42, tail: None };
assert_eq!(serde_idl::get_type(&list),
           Type::Record(vec![
               field("head", Type::Int),
               field("tail", Type::Opt(Box::new(
                   Type::Knot(TypeId::of::<List>()))))])               
);
assert_eq!(Encode!(&list),
           hex::decode("4449444c026c02a0d2aca8047c90eddae704016e00002a00").unwrap());

* Deserialization
[source,rust]
let bytes = Encode!(&[(42, "text")], &(42, "text"));
assert_eq!(bytes, hex::decode("4449444c026d016c02007c0171020001012a04746578742a0474657874").unwrap());
Decode!(&bytes, a: Vec<(i64, &str)>, b: (i64, &str));
assert_eq!(a, [(42, "text")]);
assert_eq!(b, (42, "text"));

== Remaining items
* Error handling
# Limit recursion depth for deserialization
* Ignore extra fields, future values (subtype)
* Optimize for `new struct` type
* Refactor serialization to use serde
* Import `.did` file in Rust
* Get rid of `std` dependency for `wasm` support

