= FeatureTemplate Design Doc
// Author field:
Eric Swanson <eric.swanson@dfinity.org>
v0.1, 2021-02-03
:draft:
:toc:

== Overview

Rework the asset canister so that it can store assets that are larger than
the message ingress limit.

Also, support link:https://www.notion.so/Design-HTTP-Canisters-Queries-d6bc980830a947a88bf9148a25169613[Http Canister Queries]
by associating additional metadata with each asset, and content encodings.

== Background

The asset storage canister at present is a rudimentary key/value store of static blob data.

The update call requires passing the asset content blob in its entirety, which
limits asset size to the message ingress limit.

=== Problem Statement

The main purpose is to make it so asset content length can exceed the message ingress limit.

=== Requirements

* Can upload assets of any size (within reason, say <2GB)
* Support upcoming http server

== Prior Art

S3 rest interface

* https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html
** returns Content-Type and so forth along with the body
** Note that S3 does not directly support directory structure

== Detailed Design

=== Assets

Store per asset:

* Key
** an arbitrary string that identifies the asset
* Content type
* Content for one or more content encodings
** Content encoding
** The actual content (bytes)
*** Split up into chunks for retrieval

=== Implementation

We will implement the canister in Motoko, because the canister's functionality
is within the realm of what might be found in a typical application canister.

=== Considered Solutions

==== Motoko canister

* Currently there is not a large body of Motoko libraries for things like compression
** Mitigated by: compression would probably be better done in dfx anyway

==== Rust canister with stable memory block

These notes refer to a proposed implementation mapping a FAT32 volume onto a block of stable memory.

* Affords access to general Rust libraries
* Adds complexity in managing data in stable memory
** Asset keys are not valid FAT32 paths
** Blob storage in files implies management of those files and allocation of their filenames
* Performance considerations:
** Retrieval requires reading the content out of stable memory into a blob before
returning it, since content would not be stored in contiguous memory.
** Depending on the number of asset content blobs we expect an asset canister to hold,
it might be necesary to split up the files that store content into subdirectories.

===== FAT32 implementation notes (rejected)

Note that at present the Rust CDK does not have libraries for data structures stored in stable memory.

We would use a link:https://crates.io/crates/fat32[FAT32 library] to map a FAT32 volume onto
a block of stable memory in order to store both asset metadata and content blobs.

Directory structure on this FAT32 filesystem:

----
/meta
  hex/digits/of/asset/key.can
/content
  ${blob_id}.dat
----

====== The `meta` directory

This directory stores metadata for each asset.

Since keys are of arbitrary length and can contain characters that are not valid
in FAT32 filenames, we will convert the asset key into hex digits representing the UTF-8 bytes,
and split these hex digits into groups of 8 characters, naming directories and finally a filename.

Each file will store a single Candid record:
[source, candid]
----
record {
  content_type: text;
  content: vec record {
    content_encoding: text;
    blob_id: text;
  };
};
----

====== The `content` directory

This directory stores asset content per content encoding, in individual files.

At the API level, blob ids are text (a temporary handle), only used
until the blob data is "set" on the asset.

In practice, blob ids will be numbers. To choose them, we can start with
a monotonically increasing value.

====== Blob ids

Another option would be `timestamp/sequence`, assuming only one `create_blobs` call per
canister per block height.

==== Rust canister with unstable memory

* This would be a reasonable implementation and would not require changing the interface
* Would require uploading all assets on every upgrade
** Mitigated by: only if any asset changed (not detectable at present)
* Canister-level "upgrade" would only be needed when the asset canister wasm changes
** It is not obvious how to detect this

=== Public API

[source,candid]
----

type EncodingId = text;
type Key = text;

// Create a new asset.  Contents will be attached later with SetContent.
//   - No-op if asset already exists with the same content type.
//   - Error if asset already exists with a different content type (delete first).
type CreateAssetOperation = record {
  key: Key;
  content_type: text;
};

// Add or change content for an asset, by content encoding
type SetAssetContentOperation = record {
  key: Key;
  content_encoding: text;
  encoding_id: EncodingId;
};

// Remove content for an asset, by content encoding
type UnsetAssetContentOperation = record {
  key: Key;
  content_encoding: text;
};

// Delete an asset
type DeleteAssetOperation = record {
  key: Key;
};

// Future: set up access control
type SetAssetAclOperation = record {
  key: Key;
  tbd: text;
};

// Future: set a time after which to delete an asset
type SetAssetExpiryOperation = record {
  key: Key;
  tbd: text;
};

// Reset everything
type ClearOperation = record {};

type BatchOperationKind = variant {
  Create: CreateAssetOperation;
  SetContent: SetAssetContentOperation;

  UnsetContent: UnsetAssetContentOperation;
  Delete: DeleteAssetOperation;

  SetAcl: SetAssetAclOperation;
  SetExpiry: SetAssetExpiryOperation;

  Clear: ClearOperation;
};

service: {

  get: (record {
    key: Key,
    accept_encodings: vec text
  }) -> (record {
    contents: blob; // may be the entirely of the content, or just chunk index 0
    content_type: text;
    content_encoding: text,
    chunks: nat32
  }) query;

  // if get() returned chunks > 1, call this to retrieve them.
  // chunks may or may not be split up at the same boundaries as presented to set_encoding_chunk().
  get_chunk: (record {
    key: Key,
    content_encoding: text,
    index: nat32
  }) -> (record { contents: blob }) query;

  list: (record {}) -> (vec record {
    key: Key;
    content_type: text;
    encodings: vec record {
      content_encoding: text;
    };
  }) query;

  // allocate space for content encodings
  //
  // first deletes all encodings created by an earlier call to create_encodings(), that have not been set to an asset,
  // only if set_encoding_chunk() has not been called for any of those encodings within the past 5 minutes.
  create_encodings: (record {
    encoding_info: vec record { chunks: nat32 }
  }) -> (record {
    encoding_ids: vec EncodingId
  });

  // upload part of an encoding's content
  set_encoding_chunk: (record { encoding_id: EncodingId; index: nat32; contents: blob }) -> ();

  // Perform all operations successfully, or reject
  batch: (vec BatchOperationKind) -> ();

  create_asset: (CreateAssetOperation) -> ();
  set_asset_content: (SetAssetContentOperation) -> ();
  unset_asset_content: (UnsetAssetContentOperation) -> ();

  delete_asset: (DeleteAssetOperation) -> ();

  set_asset_acl: (SetAssetAclOperation) -> ();
  set_asset_expiry: (SetAssetExpiryOperation) -> ();

  clear: (ClearOperation) -> ();

  // Single call to create an asset with content for a single content encoding that
  // fits within the message ingress limit.
  store: (record { key: Key; content_type: text; content_encoding: text; contents: blob }) -> ();
}

----

=== Security Considerations

For the time being, security controls will continue to be:
- assets writable only by canister owner
- assets readable by anyone

=== Performance Considerations

The size of the stable memory block in the canister will need to be
roughly double the size required to hold only the assets, because
during upgrades all of the new assets will briefly be stored along
with all of the previous assets.

The `dfx install` process could be smarter, for example only uploading
changed assets.  This would require more metadata, such as a hash
per content type/content blob.

These API methods are structured to facilitate efficient upload of many assets
within a single block:

* `create_blobs` (call once)
* `write_blob` (call many times concurrently)
* `batch` (call once)


== Breaking Changes

This feature breaks the signature of the `store` method.

=== Deprecation

This feature deprecates the `retrieve` method.

== Lifecycle

=== Integration Plan

The JavaScript agent will need to change in order to use the new interface.

The process that `dfx install` uses to synchronize assets to an asset canister will
be more complex.

=== Maintenance Plan

The API operation parameters are passed as a record in order to facilitate future changes.
