= FeatureTemplate Design Doc
v0.1, 2020-01-01
:draft:
:toc:

== Overview
`dfx` is to support subcommands provided as external extensions.

== Background

We wish dfx to be the focal point for developer command line tools, providing all that a developer needs for typical command line operations, but wish to keep the dfx codebase small.  Extended functionality is to be provided by external codebases that integrate with dfx.

=== Problem Statement
////
:required:

State the problem this design solves, in a concise way. A few sentences, not more.
////

=== Requirements
////
:optional:

State which requirements are necessary to consider this problem solved. This is in
relation to the solution, not the problem.
////

== Expected User/Developer Experience
////
:required: Either User and/or Developer experience should be explained.

Describe what
////

== Prior Art

=== Git extensions
==== Git: Where do extensions live?
Any command in the path that starts with `git-` is treated as a git subcommand.  Try this:

```
$ echo echo hello git | sudo install -m 755 /dev/stdin /usr/local/bin/git-hello
$ git hello
hello git
```

==== Git: listing extensions
`git` has very many subcommands.  `git --help` lists a few core commands, that is all.  To list all, use `git --help --all`.  This prints commands grouped into sections.  There is a secttion for third party commands:

```
$ git help --all | cat
See 'git help <command>' to read about a specific subcommand

Main Porcelain Commands
   add                  Add file contents to the index
[snip]
   notes                Add or inspect object notes
   pull                 Fetch from and integrate with another repository or a local branch
   push                 Update remote refs along with associated objects
   range-diff           Compare two commit ranges (e.g. two versions of a branch)
   rebase               Reapply commits on top of another base tip
[snip]

Ancillary Commands / Manipulators
   config               Get and set repository or global options
[snip]

Ancillary Commands / Interrogators
   annotate             Annotate file lines with commit information
   blame                Show what revision and author last modified each line of a file
[snip]

Interacting with Others
   archimport           Import a GNU Arch repository into Git
[snip]

Low-level Commands / Manipulators
   apply                Apply a patch to files and/or to the index
[snip]

Low-level Commands / Interrogators
   cat-file             Provide content or type and size information for repository objects
   cherry               Find commits yet to be applied to upstream
[snip]

External commands
   amend-author
   branch-clean
[snip]
   uuid

Command aliases
   diff-image           !f() { cd -- "${GIT_PREFIX:-.}"; GIT_DIFF_IMAGE_ENABLED=1 git diff "$@"; }; f

```

=== Rust Cargo extensions

Cargo maintains a list of installed extensions in `$CARGO_HOME/.crates.toml`.

Each cargo extension is implemented as a binary called `cargo-$EXTENSION_NAME` which is installed in `$CARGO_HOME/bin`.

Cargo sets environment variables.  These are listed here: https://doc.rust-lang.org/cargo/reference/environment-variables.html

== Detailed Design

=== APIs

=== Considered Solutions
////
:required:

What solutions were considered, with a list of pros and cons of each solutions.
////

=== Recommended Solution
////
:required:

What solution from the above are you recommending, and most importantly, WHY?
////

=== Public API

==== An extension must provide
* A name that consists of lower case letters or digits.  Precisely: `$DFX_EXTENSION_NAME ~= /[a-z][a-z0-9]*/`
* A binary or script called `dfx-$DFX_EXTENSION_NAME`.
* An extension MAY also provide subcommands of the extension, in the form of scripts or executables called `dfx-$DFX_EXTENSION_NAME-$DFX_SUBCOMMAND_NAME` where `$DFX_SUBCOMMAND_NAME ~= /[a-z][a-z0-9]*/`.  Likewise if there are sub-sub commands these MAY be provided as scripts or executables with the subcommand hierarchy delimited by hypens.

==== Core dfx shall provide

* If `dfx $EXTENSION_NAME [ARGUMENTS]` is executed then `dfx` SHALL execute the file called `dfx-$EXTENSION_NAME [ARGUMENTS]`.
* `dfx` SHALL have an internal method to list all installed extensions.
* `dfx --help` SHALL list all installed extensions, in addition to internal subcommands.
* `dfx extension list` SHALL list all installed extensions.
* `dfx extension install $EXTENSION_NAME` SHALL install the named extension.
* `dfx extension remove $EXTENSION_NAME` SHALL uninstall the named extension.


=== Prototype
////
:optional:

If a proof of concept is available, include a link to the files here (even if
it's in the same PR).
////

=== Security Considerations
////
:optional:

How will this feature impact security, and what needs to be done to keep it
secure. Considerations should include:
  - User input sanitization
  - Existing security protocols and standards
  - Permissions, Access Control and capabilities
  - Privacy, GDPR considerations, etc.
  - Anything else that can affect security and privacy.
////

=== Performance Considerations
////
:optional:

How will the feature affect speed and performance. Will there be a need to
benchmark the feature (and if so, how)? Is there any considerations to keep
in mind for avoiding and preventing future regressions?
////

== Breaking Changes
////
:optional:

Does this feature create or require breaking changes?
////

=== Deprecation
////
:optional:

Does this feature deprecates any existing APIs?
////

== Documentation
////
:required:

How will this feature be documented? Which people need to be involved?
////

== Lifecycle

=== Integration Plan
////
:optional: Required if there are interactions with other tools.

How will this feature interact with other tools? Is there any changes outside
of the SDK that are required to make this feature work? Does this feature
have integration with `dfx`?
////

=== Publishing Plan
////
:optional: Required if there are new packages.

Explain which new packages will be released and published with this feature.
Include any changes to current released packages.
////

=== Rollout / Migration
////
:optional:

How can we minimize impact to users? How do we maximize adoption?
////

=== Rollback Plan
////
:optional:

How do you plan to rollback the change if a major issue is found?
////

=== Maintenance Plan
////
:required:

How do you plan to maintain this feature for the next years? Can the
APIs be cleanly evolved? Can Breaking Changes in the future be avoided?

If this is a service, what is the update and monitoring strategy?

If this is a package, how do we plan to publish and deploy it? This includes
version numbering.
////

== Work Breakdown
////
:required:

Description of the various phases and milestones. This is supposed to be a
bullet point list of high level stories and tasks. It is not meant to be a
1:1 ratio of PRs.
////
