#! /nix/store/06z61jbgs0vkw4i9cqqf9yl7zsfkkhw2-bash-4.4-p23/bin/bash -e
export ASC_RTS=${ASC_RTS-'/nix/store/wdrs7d9diivspgkzg2f6z5ji2gykw9k6-asc/rts/as-rts.wasm'}
exec -a "$0" "/nix/store/wdrs7d9diivspgkzg2f6z5ji2gykw9k6-asc/bin/.asc-wrapped"  "${extraFlagsArray[@]}" "$@"
