= dfx

== Developing

Run `nix-shell` in this directory to bring the right version of `rustc` and
`cargo` into scope. Inside the shell use `cargo` to build and test the Rust
packages (crates).

== Installing from source

If you want to install `dfx` from source via nix, you can run, in the top level directory,

[source,bash]
nix-env -iA dfx.standalone -f .

To create the tarball that would be uploaded as part of a release, run

[source,bash]
nix-build -A dfx-release

and look in `result/dfx-latest.tar.gz`.

== Documentation

https://hydra.oregon.dfinity.build/latest/dfinity-ci-build/sdk/dfx.doc.x86_64-linux/dfx/index.html[Latest cargo docs].

== CI

To run the CI job manually either run:

`nix-build ci/ci.nix -A dfx[.x86_64-linux|.x86_64-darwin]`

== Dependencies

=== Licenses

https://hydra.oregon.dfinity.build/latest/dfinity-ci-build/sdk/licenses.dfx.x86_64-linux/licenses.dfinity-sdk-dfx.html[Latest licenses of all dependencies of dfx (build for x86_64-linux)].

=== Visualization

https://hydra.oregon.dfinity.build/latest/dfinity-ci-build/sdk/dfx.x86_64-linux/dfx/cargo-graph.svg[Access the latest graph of dependencies between crates of the `dfx` crate (build for x86_64-linux)].

To build and visualize this graph locally run:

`open $(nix-build -A dfx.doc)/dfx/cargo-graph.svg`
