[advisories]
ignore = [
  "RUSTSEC-2024-0437", # protobuf, it is only used in the monorepo, which forbids using the affected type
  "RUSTSEC-2026-0001", # rkyv - transitive via rust_decimal, rkyv feature not used
  "RUSTSEC-2026-0037", # quinn-proto - transitive via reqwest/ic-agent, quinn feature not used
]