= Release process

This document describes the release process for the DFINITY SDK, with step-by-step instructions, information about automation, and a checklist.

== Overview

Before starting the release process, the team should conduct a brief Go/No-Go release review to evaluate the current state of fixes and features ready to be included in a release candidate.
After reviewing the list of fixes and features, the team will decide whether to proceed with staging a build.

If the new release is given the Go green light, two people who are familiar with the process—a *driver* and a *validator*—use the checklist in this document to stage or promote a release candidate.

The *validator* should be the person most familiar with the process and be able to assist with debugging or resolving issues if the *driver* building the release runs into trouble. 

A successful release is the result of coordination between automation, manual steps performed by team members, and a validation process.
Our goal is to update this document with the latest information as we iterate to improve the release process. 

== Checklist

[%interactive]
* [ ] Participants:
** [ ] Driver
** [ ] Validator
** [ ] CI (system up)
* [ ] Is master green?
* [ ] Was master red recently or flaky?
* [ ] Follow process:
   . [ ] Update cargo version
     * [ ] `dfx/Cargo.toml`
     * [ ] `public/manifest.json` (only adding the version to the list)
     * [ ] `Cargo.lock`
   . [ ] Update manifest to include new version; *Ensure* latest remains the same.
   . [ ] Create a pull request with the above 2 changes and get the validator to approve it.
   . [ ] Switch to stable branch and run `git pull origin stable`.
   . [ ] Run `git pull origin master --ff-only`.
   . [ ] Create a tag by running `git tag -a <version> -m " Release: <version>"`.
   . [ ] Double-check the tag points to the correct version and that the tag has an annotation using `git log` and  `git describe --always` commands.
   . [ ] Push the tag first to avoid triggering hydra incorrectly by running the `git push origin version` command.
   . [ ] Push the stable branch by running the `git push origin stable` command.
   . [ ] Check hydra CI for a successful build.
   . [ ] Notify team members that the new build is ready for manual installation and testing using the `DFX_VERSION=<version>` environment variable.
   . [ ] Update release notes and documentation based on the Go/No-go list of merged PRs.
   . [ ] Prepare a PR for manifest.
   . [ ] Update the manifest once all builds are done (see https://blobules.dfinity.systems/sdk-release/ and https://hydra.dfinity.systems/jobset/dfinity-ci-build/sdk-release)
     *  [ ] Linux
     *  [ ] Darwin
  * [ ] Tag the documentation using `git tag -a <version> -m <documentation-archive-message>`.
  * [ ] Publish the tag on the remote server using `git push origin <tagname>`.
  * [ ] Deploy updated documentation using Netlify.

Notes: We assume *upstream* is `origin`.

== Requirements and properties

 - Semi-automation
 - Consistent delivery
 - Validation
 - Rollback
 - Guardrails
 - Flexibility

== Mechanism

===  Build

Our build process is described in the `release.nix` derivation.
The `release.nix` derivation mainly invokes the `dfx-release` derivation passing the annotated tag on HEAD (which happens right now to be the stable branch). 
The `dfx-release` derivation builds the release binaries and files for each platform and generates a manifest for S3 that includes the tag name. 
The release tag allows us to keep a directory structure with all past and upcoming releases in S3.

===  CI

CI release-related operation is split into two jobsets:

 - Generation and publishing of 'install.sh' and 'manifest.json'.
 - Tagging of a commit to release, building and publishing the necessary executables and files for supported platforms.

===  Manifest

We utilize a manifest to indicate to users (and in particular to our installer and dfx executable) available and supported versions for download. 
The manifest allows us to rollback a release or remove a release from the list of supported releases. 
See link:../specification/version_management{outfilesuffix}[Version Management] for details on the format of the manifest.

The manifest is generated when a patch is applied on master by the CI.

=== Installer

The installer is generated when a patch is applied on the `master` branch by the CI.

===  Changelog

A candidate changelog is generated automatically using the respective tool (under scripts directory). 
Currently, the release notes are updated manually in github.

=== Publishing of artifacts

=== Process

We now summarize the release process. 
Our first step is to ensure the proper and valid state of the `master` branch.
Next, we update `cargo` and the manifest accordingly. 
We then create and push an annotated tag on the `stable` branch, generate the changelog.
The product and SDK team members can then inspect, clarify, and develop the changelog to ensure it is appropriate for public
consumption. 
After ensuring the proper artifacts are available in S3, we can now publish them by updating the manifest.

== TODOs and improvements
. version from the tag
. release stress tests
. valid json test for the manifest
