= Release process

This document describes the release process for the DFINITY SDK, with step-by-step instructions, information about automation, and a checklist.

== Overview

Before starting the release process, the team should conduct a brief Go/No-Go release review to evaluate the current state of fixes and features ready to be included in a release candidate.
After reviewing the list of fixes and features, the team will decide whether to proceed with staging a build.

If the new release is given the Go green light, two people who are familiar with the process—a *driver* and a *validator*—use the checklist in this document to stage or promote a release candidate.

The *validator* should be the person most familiar with the process and be able to assist with debugging or resolving issues if the *driver* building the release runs into trouble.

A successful release is the result of coordination between automation, manual steps performed by team members, and a validation process.
Our goal is to update this document with the latest information as we iterate to improve the release process.

== Checklist

Use this checklist to prepare a release candidate.

=== Participants:

[%interactive]

* [ ] Driver
* [ ] Validator

=== Process

[%interactive]

* [ ] Is the CI system up?

* [ ] Is master green? See link:https://github.com/dfinity-lab/sdk/commits/master[].

* [ ] Was master red recently or flaky? See link:https://github.com/dfinity-lab/sdk/commits/master[].

* [ ] Update version information
+
[width="80%",cols="2,<68%", frame=none]
|===

| | `src/dfx/Cargo.toml`

| | `src/agent/rust/Cargo.toml`

| | `src/ic_identity_manager/Cargo.toml`

| | `Cargo.lock` (can also run `cargo build`)

| | Update `+@dfinity/agent+`: `cd src/bootstrap/package.json && npm version {new_version}+`

| | Update `+@dfinity/bootstrap+`: `cd src/bootstrap/package.json && npm version {new_version}+`

| | `public/manifest.json` (add the new version to the list)

|===

* [ ] Update manifest to include new version.
+
[width="80%",cols="2,<68%", frame=none]
|===

| | *Ensure* `latest` remains the same.

|===

* [ ] Create a pull request with the above changes and get the validator to approve it.
+
[width="80%",cols="2,<68%", frame=none]
|===
| | `git switch -c <name>/<version>`
| | `git commit -m "chore: release <version>`
| | Apply `automerge-squash` label and wait for pull request to get merged.
|===

* [ ] Switch to stable branch by running `git switch stable`, then run `git pull origin stable`.

* [ ] Run `git pull origin master --ff-only`.

* [ ] Create a tag by running `git tag -a <version> -m "Release: <version>"`.

* [ ] Verify the tag points to the correct version and includes annotation.
+
[width="80%",cols="2,<68%", frame=none]
|===
| | `git log`
| | `git describe --always`
|===


* [ ] Push the tag by running the `git push origin <version>` command.
+
[width="80%",cols="2,<68%", frame=none]
|===
| | CI will only publish dfx from the latest commit from the stable branch when that commit is tagged with a version.
|===

* [ ] Push the `stable` branch by running the `git push origin stable` command.
+
[width="80%",cols="2,<68%", frame=none]
|===
| | Pushing the branch second is an optimization.
Hydra will spur into action when stable advances so if the branch is already tagged it won't require a second fetch.
|===

* [ ] Wait for the automatic slack message to
link:https://dfinity.slack.com/archives/CUXGQBABF/p1594954197000100[_#build-notifications_]
about the successful publishing of the dfx tarballs

* [ ] Notify team members that the new build is ready for manual installation and testing.

* [ ] Install the build using the `DFX_VERSION=<version>` environment variable.

* [ ] Run through the link:https://staging--eloquent-poitras-af14f0.netlify.app/docs/index.html[_Quick start_] steps.

* [ ] Update release notes and documentation based on the Go/No-go list of merged PRs.

=== Before promoting the release to latest

[%interactive]

* [ ] Verify that the `+hello+` project can be built, deployed, called in a terminal, and viewed in a browser.
  . `+nix-build ./dfx.nix -A build+` to build the dfx binary
+
(_for the rest of these instructions, assume that `+dfx+` is a reference to `result/bin/dfx or wherever the binary was built with this command`_)
+
. `dfx new {name}` to generate default new project
. `dfx start`
. In a new terminal
    .. `+dfx canister create --all+`
    .. `+dfx build+`
    .. `+dfx canister install --all+`
. Open candid ui (e.g. replica running at port 8000: http://localhost:8000/candid?canisterId=12345)
    ** [ ] verify UI loads
    ** [ ] verify no errors in console
* [ ] Verify that release notes and documentation are ready for public consumption.

=== Promote the release

[%interactive]

* [ ] Prepare a PR for the manifest.

* [ ] Verify all builds are done.
+
[width="80%",cols="2,<68%", frame=none]
|===
| | link:https://download.dfinity.systems/sdk/dfx/{DFX_VERSION}/x86_64-linux/dfx-{DFX_VERSION}.tar.gz[]
| | link:https://download.dfinity.systems/sdk/dfx/{DFX_VERSION}/x86_64-darwin/dfx-{DFX_VERSION}.tar.gz[]
| | link:https://hydra.dfinity.systems/jobset/dfinity-ci-build/sdk-release[]
|===

* [ ] Update the manifest.
+
[width="80%",cols="2,<68%", frame=none]
|===
| | Linux
| | Darwin
|===
+
Note: We assume *upstream* is `origin`.

=== Release documentation

link:https://github.com/dfinity/docs[Documentation repo]

[%interactive]

* [ ] Tag the documentation using `git tag -a <version> -m <documentation-archive-message>`.

* [ ] Publish the tag on the remote server using `git push origin <tagname>`.

* [ ] Deploy updated documentation using Netlify.

== Requirements and properties

 - Semi-automation
 - Consistent delivery
 - Validation
 - Rollback
 - Guardrails
 - Flexibility

== Build mechanism

Our build process is described in the `release.nix` derivation.
The `release.nix` derivation mainly invokes the `dfx-release` derivation passing the annotated tag on HEAD (which happens right now to be the stable branch).
The `dfx-release` derivation builds the release binaries and files for each platform and generates a manifest for S3 that includes the tag name.
The release tag allows us to keep a directory structure with all past and upcoming releases in S3.

==  CI

CI release-related operation is split into two jobsets:

 - Generation and publishing of 'install.sh' and 'manifest.json'.
 - Tagging of a commit to release, building and publishing the necessary executables and files for supported platforms.

==  Manifest

We utilize a manifest to indicate to users (and in particular to our installer and dfx executable) available and supported versions for download.
The manifest allows us to rollback a release or remove a release from the list of supported releases.
See link:../specification/version_management{outfilesuffix}[Version Management] for details on the format of the manifest.

The manifest is generated when a patch is applied on master by the CI.

== Installer

The installer is generated when a patch is applied on the `master` branch by the CI.

==  Changelog

A candidate changelog is generated automatically using the respective tool (under scripts directory).
Currently, the release notes are updated manually in github.

== Publishing of artifacts

We now summarize the release process.
Our first step is to ensure the proper and valid state of the `master` branch.
Next, we update `cargo` and the manifest accordingly.
We then create and push an annotated tag on the `stable` branch, generate the changelog.
The product and SDK team members can then inspect, clarify, and develop the changelog to ensure it is appropriate for public
consumption.
After ensuring the proper artifacts are available in S3, we can now publish them by updating the manifest.

== TODOs and improvements
. version from the tag
. release stress tests
. valid json test for the manifest
