#!/usr/bin/expect -df

# ASSUMPTION: init_alice_with_pw.exp run before this script

match_max 100000
set timeout 30

spawn dfx ledger balance --network ic --identity alice
expect "Please enter the passphrase for your identity: "
send -- "testpassword\r"
expect "Decryption complete.\r"
expect {
    "WARN" {
        puts stderr "Warned incorrectly for an encrypted identity"
        exit 1
    }
    eof {}
}
