#!/usr/bin/expect -df

match_max 100000
set timeout 30

spawn dfx new e2e_project
expect "Select a backend language:"
# down arrow, Rust should be option 2
send "\033\[B"
send "\r"

expect "Select a frontend framework:"
# no down arrow, Svelte should be option 1
send "\r"
# first and third, should be II and frontend tests respectively
expect "Add extra features"
send " "
send "\033\[B\033\[B"
send " "
send "\r"
expect eof
