name: Check frontend canister build (skipped)

on: 
  push:
    branches:
      - master
    paths:
      - src/distributed/assetstorage.wasm.gz
      - src/canisters/frontend/ic-certified-assets/**
      - src/canisters/frontend/ic-frontend-canister/**
  pull_request:
    paths:
      - src/distributed/assetstorage.wasm.gz
      - src/canisters/frontend/ic-certified-assets/**
      - src/canisters/frontend/ic-frontend-canister/**

jobs:
  frontend:
    runs-on: ubuntu-latest
    name: frontend-canister-up-to-date:required
