name: Check cargo build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  builds:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [ '1.52.1' ]
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup component add clippy
          rustup default ${{ matrix.rust }}

      - name: Check cargo build
        run: cargo build
