name: "Check binaries"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: [ macos-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - run: ./scripts/check-binaries.sh
