name: Conventional Commit Validation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Check commits
        uses: commitsar-app/commitsar@v0.11.2
