name: PR title format
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # When getting Rust dependencies, retry on network error:
  CARGO_NET_RETRY: 10
  # Use the local .curlrc
  CURL_HOME: .

jobs:
  check:
    name: conventional-pr-title:required
    runs-on: ubuntu-latest
    steps:
        # Conventional commit patterns:
        #   verb: description
        #   verb!: description of breaking change
        #   verb(scope): Description of change to $scope
        #   verb(scope)!: Description of breaking change to $scope
        # verb: feat, fix, ...
        # scope: refers to the part of code being changed.  E.g. " (accounts)" or " (accounts,canisters)"
        # !: Indicates that the PR contains a breaking change.
      - run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ^(feat|fix|chore|build|ci|docs|style|refactor|perf|test)(\([-a-zA-Z0-9,]+\))?\!?\: ]]; then
              echo pass
          else
              echo "PR title does not match conventions"
              echo "PR title: ${{ github.event.pull_request.title }}"
              exit 1
          fi
