name: Lint

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # When getting Rust dependencies, retry on network error:
  CARGO_NET_RETRY: 10
  # Use the local .curlrc
  CURL_HOME: .
  # Disable DFX telemetry
  DFX_TELEMETRY: 'off'

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      sources: ${{ steps.filter.outputs.sources }}
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'push'
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            sources:
              - .github/workflows/lint.yml
              - src/**
              - Cargo.lock
              - Cargo.toml
              - rust-toolchain.toml

  test:
    name: lint
    if: needs.changes.outputs.sources == 'true'
    needs: changes
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm, macos-15, windows-2025 ]

    steps:
      - uses: actions/checkout@v4

      # This step also handles Rust-specific caching
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Lint
        run: cargo clippy --verbose --tests --benches --workspace -- -D warnings
        env:
          RUST_BACKTRACE: 1

  aggregate:
    name: lint:required
    if: always() && needs.changes.outputs.sources == 'true'
    needs: [changes, test]
    runs-on: ubuntu-latest
    steps:
      - name: check step result directly
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
