name: Publish dfxvm install script

on:
  push:
    branches:
      - sdk-1278-dfxvm-install-script

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # When getting Rust dependencies, retry on network error:
  CARGO_NET_RETRY: 10
  # Use the local .curlrc
  CURL_HOME: .

jobs:
  publish-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shfmt
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest
      - name: Generate
        run: |
          shellcheck --shell=sh public/install/*.sh --exclude SC2154,SC2034,SC3003,SC3014,SC3043
          ~/go/bin/shfmt -d -p -i 4 -ci -bn -s public/install/*.sh
          sed -i "s/@revision@/${GITHUB_SHA}/" public/install/999_footer.sh
          mkdir _out
          cat public/install/*.sh > _out/install.sh
          sed -i "
            /#!.*/p
            /##.*/p
            /^ *$/d
            /^ *#/d
            s/ *#.*//
          " _out/install.sh
      - name: Upload Artifacts
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          single_commit: yes
          branch: dfxvm-install-script
          folder: _out/
