name: ci

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "install wasmtime"
      run: |
       mkdir /home/runner/bin
       echo "/home/runner/bin" >> $GITHUB_PATH
       wget https://github.com/bytecodealliance/wasmtime/releases/download/v0.18.0/wasmtime-v0.18.0-x86_64-linux.tar.xz
       tar xf wasmtime-v0.18.0-x86_64-linux.tar.xz
       cp wasmtime-v0.18.0-x86_64-linux/wasmtime /home/runner/bin/wasmtime
    - name: "install vessel"
      run: |
       wget --output-document /home/runner/bin/vessel https://github.com/kritzcreek/vessel/releases/download/v0.6.0/vessel-linux64
       chmod +x /home/runner/bin/vessel
    - name: "check"
      run: make check-strict
    - name: "test"
      run: make test
    - name: "docs"
      run: make docs
